# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: News
    url: 'post/news'
    weight: 15
  - name: Featured
    url: '#featured'
    weight: 20
  - name: Papers
    url: publication/
    weight: 25
  - name: Github
    url: https://github.com/deleeuw
    weight: 35
  - name: YouTube
    url: https://www.youtube.com/c/JanDeleeuw/videos
    weight: 40
  - name: Interview
    url: post/wijsen
    weight: 45
  - name: 'Say My Name'
    url: post/name
    weight: 50
  - name: 'SimpleAnalytics'
    url: https://dashboard.simpleanalytics.com/jansweb.netlify.app
    weight: 55

