johnson <-
structure(list(MATHEMATICS = c("D", "D", "B", "D", "A", "B", 
"D", "C", "C", "B", "A", "F", "F", "D", "B", "A", "D", "C", "F", 
"B", "D", "D", "A", "D", "C", "C", "C", "B", "D", "B", "B", "C", 
"B", "C", "C", "C", "B", "D", "B", "B"), CHEMISTRY = c("C", "A", 
"B", "C", "A", "B", "C", "C", "C", "B", "C", "D", "D", "C", "B", 
"A", "C", "C", "D", "B", "F", "B", "A", "D", "C", "C", "B", "C", 
"C", "B", "B", "C", "C", "B", "B", "C", "B", "C", "A", "A"), 
    ENGLISH = c("C", "C", "C", "C", "B", "B", "B", "C", "C", 
    "A", "C", "C", "D", "B", "B", "B", "D", "D", "F", "A", "C", 
    "B", "B", "F", "B", "D", "C", "C", "B", "C", "D", "C", "B", 
    "C", "A", "C", "D", "B", "B", "C"), DRAWING = c("C", "B", 
    "B", "B", "C", "B", "B", "C", "B", "B", "B", "B", "D", "D", 
    "C", "B", "C", "B", "F", "A", "B", "B", "C", "C", "C", "B", 
    "A", "C", "B", "C", "C", "A", "C", "B", "B", "C", "C", "C", 
    "C", "B")), class = "data.frame", row.names = c(NA, -40L))
